# Generated by Django 4.1.4 on 2022-12-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'admin'), ('B', 'buyers'), ('S', 'sellers')], max_length=1),
        ),
    ]
