# Generated by Django 4.1.4 on 2022-12-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_palced',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordersitem',
            name='seller_item',
        ),
        migrations.AlterField(
            model_name='ordersitem',
            name='item',
            field=models.TextField(max_length=100),
        ),
    ]
