# Generated by Django 4.1.4 on 2022-12-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_item_item_name'),
        ('orders', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_qty',
            field=models.IntegerField(),
        ),
    ]
