# Generated by Django 4.1.4 on 2022-12-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
